version: "3"

services:
  back:
    build:
      context: .
      dockerfile: app/Dockerfile #Dockerfileの場所
    volumes:
      - ./app:/go/src/app
    ports:
      - "5555:8080"
    tty: true #コンテナ永続化
    depends_on:
      - mysql

  #mysql:
  #  build: ./mysql/
  #  volumes:
      # 初期データを投入するSQLが格納されているdir
      # - ./mysql/init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
  #    - ./mysql/data:/var/lib/mysql
  #  environment:
  #    - MYSQL_DATABASE=echo
  #    - MYSQL_USER=echo
  #    - MYSQL_PASSWORD=golang
  #    - MYSQL_ROOT_PASSWORD=golang
  #  ports:
  #    - "3355:3306"
  mysql:
    container_name: mysql
    image: mysql:8.0
    # 従来の認証方式にしておく
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-store:/var/lib/mysql:cached
      - ./logs:/var/log/mysql
    environment:
      - MYSQL_DATABASE=echo
      - MYSQL_ROOT_PASSWORD=golang
      - MYSQL_USER=echo
      - MYSQL_PASSWORD=golang
      - TZ=Asia/Tokyo
    ports:
      - "3355:3306"

volumes: # データの永続化
  db-store:
